spring.application.name=api-gateway
server.port=8088

spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Service URLs
service.user.url=http://user-service
service.product.url=http://product-service
service.cart.url=http://cart-service
service.order.url=http://order-service

logging.level.org.springdoc=DEBUG
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
