spring:
  application:
    name: product-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      function:
        definition: orderCanceledEventConsumer
      bindings:
        orderCanceledEventConsumer-in-0:
          destination: order-events
          group: product-service

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8092