server:
  port: 8085

spring:
  application:
    name: composition-service

  graphql:
    graphiql:
      enabled: true
    schema-locations: classpath:graphql/schema.graphqls
    web-url: /graphql
    path: /graphql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    at.fhv.compositionservice: DEBUG
    org.springframework.graphql: DEBUG